<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class creatRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [

                'key' => 'required',
                'agent' => 'required|min:3|max:25',
                'title' => 'required',
                'country' => 'required',
//                'category' => 'required',
                'room' => 'required'

        ];
    }

    public  function attributes()
    {
        return [
            'key' => 'key',

        ];
//        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function messages()
    {
        return[
            'key.required' => 'key datark e',
            'agent.required' => 'agent datark e',
            'agent.min' => 'agent min:3',
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
